version: '3'
services:
    taraxa-node-testnet-1:
        container_name: taraxa-node-testnet-1
        image: taraxa/taraxa-node:latest
        ports:
            - "10002:10002"
            - "7777:7777"
            - "8777:8777"
        expose:
            - "10002"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet1:/taraxadb
            - ./conf/conf_taraxa1.json:/config/conf_taraxa.json
        networks:
            testnet_network:
                ipv4_address: 172.28.1.1
    taraxa-node-testnet-2:
        container_name: taraxa-node-testnet-2
        image: taraxa/taraxa-node:latest
        ports:
            - "10003:10003"
            - "7778:7778"
            - "8778:8778"
        expose:
            - "10003"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet2:/taraxadb
            - ./conf/conf_taraxa2.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.2
    taraxa-node-testnet-3:
        container_name: taraxa-node-testnet-3
        image: taraxa/taraxa-node:latest
        ports:
            - "10004:10004"
            - "7779:7779"
            - "8779:8779"
        expose:
            - "10004"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet3:/taraxadb
            - ./conf/conf_taraxa3.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.3
    taraxa-node-testnet-4:
        container_name: taraxa-node-testnet-4
        image: taraxa/taraxa-node:latest
        ports:
            - "10005:10005"
            - "7780:7780"
            - "8780:8780"
        expose:
            - "10005"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet4:/taraxadb
            - ./conf/conf_taraxa4.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.4
    taraxa-node-testnet-5:
        container_name: taraxa-node-testnet-5
        image: taraxa/taraxa-node:latest
        ports:
            - "10006:10006"
            - "7781:7781"
            - "8781:8781"
        expose:
            - "10006"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet5:/taraxadb
            - ./conf/conf_taraxa5.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.5
            
networks:
    testnet_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16