version: '3'
services:
    taraxa-node-testnet-1:
        container_name: taraxa-node-testnet-1
        image: taraxa/taraxa-node:latest
        restart: always
        ports:
            - "10002:10002"
            - "10002:10002/udp"
            - "7777:7777"
            - "8777:8777"
        expose:
            - "10002"
            - "7777"
            - "8777"
        command: ["--conf_taraxa", "/config/conf_taraxa.json", "--boot_node"]
        volumes:
            - ~/.taraxa-node/db/testnet1:/taraxadb
            - ./dockerfiles/conf_taraxa1.json:/config/conf_taraxa.json
        networks:
            testnet_network:
                ipv4_address: 172.28.1.1
    taraxa-node-testnet-2:
        container_name: taraxa-node-testnet-2
        image: taraxa/taraxa-node:latest
        restart: always
        ports:
            - "10003:10003"
            - "10003:10003/udp"
            - "7778:7778"
            - "8778:8778"
        expose:
            - "10003"
        command: ["--conf_taraxa", "/config/conf_taraxa.json"]
        volumes:
            - ~/.taraxa-node/db/testnet2:/taraxadb
            - ./dockerfiles/conf_taraxa2.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.2
    taraxa-node-testnet-3:
        container_name: taraxa-node-testnet-3
        image: taraxa/taraxa-node:latest
        restart: always
        ports:
            - "10004:10004"
            - "10004:10004/udp"
            - "7779:7779"
            - "8779:8779"
        expose:
            - "10004"
        command: ["--conf_taraxa", "/config/conf_taraxa.json"]
        volumes:
            - ~/.taraxa-node/db/testnet3:/taraxadb
            - ./dockerfiles/conf_taraxa3.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.3
    taraxa-node-testnet-4:
        container_name: taraxa-node-testnet-4
        image: taraxa/taraxa-node:latest
        restart: always
        ports:
            - "10005:10005"
            - "10005:10005/udp"
            - "7780:7780"
            - "8780:8780"
        expose:
            - "10005"
        command: ["--conf_taraxa", "/config/conf_taraxa.json"]
        volumes:
            - ~/.taraxa-node/db/testnet4:/taraxadb
            - ./dockerfiles/conf_taraxa4.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.4
    taraxa-node-testnet-5:
        container_name: taraxa-node-testnet-5
        image: taraxa/taraxa-node:latest
        restart: always
        ports:
            - "10006:10006"
            - "10006:10006/udp"
            - "7781:7781"
            - "8781:8781"
        expose:
            - "10006"
        command: ["--conf_taraxa", "/config/conf_taraxa.json"]
        volumes:
            - ~/.taraxa-node/db/testnet5:/taraxadb
            - ./dockerfiles/conf_taraxa5.json:/config/conf_taraxa.json
        depends_on:
            - taraxa-node-testnet-1
        networks:
            testnet_network:
                ipv4_address: 172.28.1.5

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        expose:
            - "27017"
        command: ["mongod"]
        volumes: 
            - ~/.mongodb:/data/db
        networks:
            - testnet_network

    # taraxa-explorer-backend:
    #     container_name: taraxa-explorer-backend
    #     image: taraxa/taraxa-explorer-backend:latest
    #     ports:
    #         - "8089:8089"
    #     volumes:
    #         - ./dockerfiles/explorer-backend.env:/app/.env
    #     depends_on:
    #         - taraxa-node-testnet-1
    #         - mongodb
    #     networks:
    #         - testnet_network
    #     command: ["python", "server/run.py"]
    # taraxa-explorer-backend-ws:
    #     container_name: taraxa-explorer-backend-ws
    #     image: taraxa/taraxa-explorer-backend:latest
    #     ports:
    #         - "9777:9777"
    #     volumes:
    #         - ./dockerfiles/explorer-backend.env:/app/.env
    #     depends_on:
    #         - taraxa-node-testnet-1
    #         - mongodb
    #     networks:
    #         - testnet_network
    #     command: ["python", "worker/run.py"]
    # taraxa-explorer-block-monitor:
    #     container_name: taraxa-explorer-block-monitor
    #     image: taraxa/taraxa-explorer-backend:latest
    #     volumes:
    #         - ./dockerfiles/explorer-backend.env:/app/.env
    #     depends_on:
    #         - taraxa-node-testnet-1
    #         - mongodb
    #     networks:
    #         - testnet_network
    #     command: ["python", "broker/run.py"]
    # taraxa-explorer-sync:
    #     container_name: taraxa-explorer-sync
    #     image: taraxa/taraxa-explorer-backend:latest
    #     volumes:
    #         - ./dockerfiles/explorer-backend.env:/app/.env
    #     depends_on:
    #         - taraxa-node-testnet-1
    #         - mongodb
    #     networks:
    #         - testnet_network
    #     command: ["python", "broker/manager.py"]
    taraxa-explorer-sync:
        container_name: taraxa-explorer-sync
        build: 
            context: .
        restart: always
        environment:
            - RPC_HTTP_PROVIDER=http://taraxa-node-testnet-1:7777
            - RPC_WS_PROVIDER=ws://taraxa-node-testnet-1:8777
            - MONGO_URI=mongodb://mongodb:27017/explorer-api-testnet
        depends_on:
            - taraxa-node-testnet-1
            - mongodb
        networks:
            - testnet_network
        command: ["node", "./worker/blockchain-sync"]
    taraxa-explorer:
        container_name: taraxa-explorer
        build: 
            context: .
        restart: always
        environment:
            - MONGO_URI=mongodb://mongodb:27017/explorer-api-testnet
        depends_on:
            - taraxa-node-testnet-1
            - mongodb
        ports:
            - "3000:3000"
        networks:
            - testnet_network
        command: ["npm", "start"]
    taraxa-explorer-wsserver:
        container_name: taraxa-explorer-wsserver
        build: 
            context: .
        restart: always
        environment:
            - MONGO_URI=mongodb://mongodb:27017/explorer-api-testnet
        ports:
            - "3001:3001"
        depends_on:
            - taraxa-node-testnet-1
            - mongodb
        networks:
            - testnet_network
        command: ["node", "./ws-server"]
            
networks:
    testnet_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16