apiVersion: v2
appVersion: "1.0"
description: Taraxa's block explorer. Helm chart.
name: explorer
version: 0.2.0
dependencies:
  - name: mongodb
    version: 11.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
