apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "explorer.delegation.fullname" . }}
  labels:
    {{- include "explorer.delegation.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "explorer.delegation.fullname" . }}
  selector:
    matchLabels:
      {{- include "explorer.delegation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.delegation.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "explorer.delegation.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "explorer.delegation.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.delegation.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-rpc-node
          image: dwdraju/alpine-curl-jq:latest
          command: ["/bin/entrypoint.sh"]
          args: ["{{ .Values.configEnvs.rpcHttpProvider }}"]
          volumeMounts:
            - name: rpc-node-check
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
      containers:
        - name: {{ include "explorer.delegation.fullname" . }}
          securityContext:
            {{- toYaml .Values.delegation.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./worker/delegation.js"]
          env:
            - name: FAUCET_PRIV_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "explorer.faucet.fullname" . }}
                  key: faucetPrivkey
            - name: RPC_HTTP_PROVIDER
              value: {{ .Values.configEnvs.rpcHttpProvider | quote }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGO_URI
              value: {{ template "mongodb.url" . }}
            {{- else }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "explorer.fullname" . }}
                  key: mongoUri
            {{- end }}
            {{- if .Values.configEnvs.appsignalPushKey }}
            - name: APPSIGNAL_PUSH_API_KEY
              value: {{ .Values.configEnvs.appsignalPushKey | quote }}
            {{- end }}
            {{- if .Values.configEnvs.appsignalProjectName }}
            - name: APPSIGNAL_PROJECT_NAME
              value: {{ .Values.configEnvs.appsignalProjectName | quote }}
            {{- end }}
          resources:
              {{- toYaml .Values.delegation.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/taraxa
      volumes:
        - name: rpc-node-check
          configMap:
            defaultMode: 0700
            name: {{ include "explorer.fullname" . }}-rpc-node-check
        - name: config
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.delegation.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.delegation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
