{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explorer.faucet.fullname" . }}
  labels:
    {{- include "explorer.faucet.labels" . | nindent 4 }}
type: Opaque
data:
  faucetPrivkey: {{ .Values.faucet.privKey | b64enc | quote }}
{{- end }}