{{- if .Values.faucet.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "explorer.faucet.fullname" . }}
  labels: {{ include "explorer.faucet.labels" . | nindent 4 }}
{{- end }}
