---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "explorer.fullname" . }}-rpc-node-check
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #!/bin/sh
    set -e

    echo "Checking host $1"
    PAYLOAD='{"jsonrpc":"2.0","method":"get_node_status","params": [],"id":1}'

    while [ $(curl -L -sw '%{http_code}' -X POST -H 'Content-Type: application/json' -d "${PAYLOAD}" $1 -o /dev/null) -ne 200 ]; do
      sleep 5
      echo 'Waiting for the RPC node...'
    done
