{{- if not .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
type: Opaque
data:
  mongoUri: {{ .Values.mongoUri | b64enc | quote }}
{{- end }}