apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "explorer.stats.fullname" . }}
  labels:
    {{- include "explorer.stats.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "explorer.stats.fullname" . }}
  selector:
    matchLabels:
      {{- include "explorer.stats.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.stats.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "explorer.stats.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "explorer.stats.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.stats.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "explorer.stats.fullname" . }}
          securityContext:
            {{- toYaml .Values.stats.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "address-stats"]
          env:
            - name: RPC_HTTP_PROVIDER
              value: {{ .Values.configEnvs.rpcHttpProvider | quote }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGO_URI
              value: {{ template "mongodb.url" . }}
            {{- else }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "explorer.fullname" . }}
                  key: mongoUri
            {{- end }}
            {{- if .Values.configEnvs.appsignalPushKey }}
            - name: APPSIGNAL_PUSH_API_KEY
              value: {{ .Values.configEnvs.appsignalPushKey | quote }}
            {{- end }}
            {{- if .Values.configEnvs.appsignalProjectName }}
            - name: APPSIGNAL_PROJECT_NAME
              value: {{ .Values.configEnvs.appsignalProjectName | quote }}
            {{- end }}
          resources:
              {{- toYaml .Values.stats.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stats.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stats.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
