apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "explorer.syncer.fullname" . }}-restarter
  labels: {{ include "explorer.syncer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: ["{{ include "explorer.syncer.fullname" . }}"]
    verbs: ["get", "patch", "list", "watch"]