apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "explorer.syncer.fullname" . }}-restarter
  labels: {{ include "explorer.syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "explorer.syncer.fullname" . }}-restarter
subjects:
  - kind: ServiceAccount
    name: {{ template "explorer.syncer.fullname" . }}-restarter
